version: '3.8'

services:
  laravel-api:
    build:
      context: ../   # Path to the Dockerfile
      dockerfile: docker/Dockerfile
    image: laravel-api
    container_name: laravel-api
    networks:
      - app-network
    environment:
      #- APP_ENV=production
      #- APP_KEY=your-app-key  # You should generate and use an actual APP_KEY
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=test3
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass@word1
    volumes:
      - ./../laravel:/var/www/html  # Mount Laravel project directory
    expose:
      - "9000"  # Expose PHP-FPM port internally for Nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"     # Expose HTTP port
      #- "443:443"   # Expose HTTPS port (optional for SSL)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount the custom Nginx config
      - ./../laravel:/var/www/html  # Mount the Laravel directory
    networks:
      - app-network
    depends_on:
      - laravel-api  # Ensure Laravel container is started before Nginx

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: test3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass@word1
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"  # Expose the PostgreSQL port internally

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
