apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 9000  # The port the container exposes
      targetPort: 9000
  clusterIP: None  # Since it's accessed internally by Nginx, no need for external access
