apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort      # Change to NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Define an accessible port (you can choose another port)
  selector:
    app: nginx

