apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;  # Or your domain

      root /var/www/html/public;  # Path to Laravel's public folder inside the container
      index index.php index.html index.htm;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          fastcgi_pass laravel-app:9000;  # PHP-FPM container, port 9000
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;  # Simplified version
          include fastcgi_params;
      }

      location ~ /\.ht {
          deny all;  # Block access to .htaccess files for security
      }

      # Optionally, handle static file caching for better performance in production
      location ~* \.(?:css|js|jpg|jpeg|gif|png|webp|svg|ttf|woff|woff2|eot|otf|json|xml)$ {
          expires 30d;
          add_header Cache-Control "public";
      }
    }

